version: '3.8'

services:
  it-asset-tracker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: it-asset-tracker
    ports:
      - "9010:9010"
    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: 1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9010"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s